### ISSUE TITLE
If a non PTE/GTE adds a comment, no warning is shown

### ISSUE THREAD

**Issue by amieiro** [GlotPress/gp-translation-helpers#17] opened 2022-02-09 09:25 UTC
I think the handling of submitting comments needs improvement
In the following situations, clicking the Post Comment button does not show warnings

1. Empty translation
2. Translation entered but not saved
3. If no topic is selected
4. translation suggested and reopened.

If an admin submits a comment it also needs improvement, no warning shown

1. No topic selected.

This issue was created by @psmits1567 [here](https://github.com/WordPress/translate-w-org-env/issues/2).

**Comment by akirk** [comment] 2022-03-07 13:25
Validation for the form has been enabled in #34, we need to test what is still broken here.

**Comment by psmits1567** [comment] 2022-03-17 14:23
Issue 1 of my list is not solved, you can give feedback on an empty translation. This can cause spam in my opinion
Steps to reproduce:
1. Open a project, select a non translated original, open feedback, select a reason and enter some comment, submit this
The feedback is added
Issue 2 The same happens when you do enter a translation, but do not save it
Issue 3 of my list is solved
Issue 4 is solved because yo now get to see that you did not select a topic

**Comment by amieiro** [comment] 2022-10-03 12:11
Hi, @psmits1567 

I am reviewing this issue and I see you detect some errors in the 1st and 2nd situations. You talk about give feedback to a string without translation, because we can get some spam. I don't see any problem, because:
- The user needs to be logged, so if we have some spammy users, we can block them, as we do in the forums.
- It is a normal usage for an empty translation to:
  - Give feedback to the developers about an incorrect original or request more context for the original.
  - Get feedback about the future translation from a GTE/PTE/CLPTE.

I think we can close this issue. Can you confirm it? Thank you.

**Comment by psmits1567** [comment] 2022-10-03 12:20
Yes you can close it

**Closed** 2022-10-03 12:33 UTC
